// <auto-generated />
using System;
using Lumen.Modules.GRDF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lumen.Modules.GRDF.Data.Migrations
{
    [DbContext(typeof(GRDFContext))]
    [Migration("20250808093655_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("GRDF")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lumen.Modules.GRDF.Common.Models.GRDFPointInTime", b =>
                {
                    b.Property<DateOnly>("JourneeGaziere")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("EnergieConsomme")
                        .HasColumnType("real");

                    b.Property<int>("IndexDebut")
                        .HasColumnType("integer");

                    b.Property<int>("IndexFin")
                        .HasColumnType("integer");

                    b.Property<float>("OutsideTemperature")
                        .HasColumnType("real");

                    b.Property<float>("VolumeBrutConsomme")
                        .HasColumnType("real");

                    b.Property<int>("VolumeConverti")
                        .HasColumnType("integer");

                    b.HasKey("JourneeGaziere");

                    b.ToTable("GRDF", "GRDF");
                });
#pragma warning restore 612, 618
        }
    }
}
